### ISSUE TITLE
BUG With double message!

### ISSUE THREAD

**Issue by Liopoxys** [slvlr/PM2-Plugins#10]
**What plugin is this ticket in relation to?**
Advanced Crates?

**Versions:**
 - Arclight 1.16.5:
 - Plugin Version: 3.4 since the new ones are even bugger

**Describe the bug**
My trouble is that in latest version, rewards arent announcing to players, using the finalmessage feature, and i needed to downgrade to 3.4 cause i was getting dupped rewards

**To Reproduce**
Steps to reproduce the behavior: Just have more than 5 players opening crates

**Expected behavior**
Announce correctly the message and not giving dupes.

**Screenshots**

**Error / Logs**
No error

**Comment by ThePM2** [comment]
Cant replicate this issue myself. Could you please specify:

1. Does the issue only happen when there are more than 5 people or does this happen with only 1 user online too
2. Your crate config file. Please upload it in a pastebin

**Comment by ThePM2** [comment]
user did not reply
