### ISSUE TITLE
Round & Round2 animations don't work with modded items

### ISSUE THREAD

**Issue by nicholasrobertm** [slvlr/PM2-Plugins#11]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.16.5
 - Plugin Version: 3.6.4

**Describe the bug**
When using 'Round' or 'Round2' animation with modded items, you get back an error that the material doesn't exist.

**To Reproduce**
1. Start with a working config https://pastebin.com/iqCPiwqn
2. Give yourself a key and use it on the crate, you will not receive the above error
3. Change to a non-working config https://pastebin.com/WYJk3h0G
4. Reload or restart the server
5. Open the crate again and receive the error above

**Expected behavior**
The crate opens and plays the animation before picking a reward

**Error / Logs**
https://pastebin.com/A551531F

**Config File**
https://pastebin.com/dPKu7Rki

**Crate File**
Working crate - https://pastebin.com/iqCPiwqn
Not working crate - https://pastebin.com/WYJk3h0G

**Comment by ThePM2** [comment]
Fixed in V3.6.5
