### ISSUE TITLE
Advanced crates doesn't load at all for version 3.6.52

### ISSUE THREAD

**Issue by nicholasrobertm** [slvlr/PM2-Plugins#12]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?

**Versions:**
 - Server Version: 1.16.5
 - Plugin Version: 3.6.52 (marked as 3.6.5 on the page but the download gives 3.6.52)

**Describe the bug**
Advanced crates doesn't load at all in the latest version

**To Reproduce**
Spin up a 1.16 server with the above advancedcrates version

**Expected behavior**
Advanced crates loads

**Error / Logs**
https://pastebin.com/ANDXwy38

**Config File**
Default

**Crate File**
Default

**Comment by ThePM2** [comment]
Should be ok on V3.6.6
