### ISSUE TITLE
Specialized Crates - reward setting problem

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#17]
**Plugin**: Specialized Crates 3.2.4
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Velocity**: velocity-proxy-3.1.2-SNAPSHOT-all
**Java Version**: jdk-11.0.15.1
**Explanation**: If you drag and drop a mod item into the reward setting
in '/scrate config', the material item of display-item is not created and the name of display-item is entered without a color code.
**Video**: https://youtu.be/1ic2RoGuTx4

**Comment by ThePM2** [comment]
has been fixed on V3.2.5
