### ISSUE TITLE
Specialized Crates - The problem of the lore and nbt-tags of the written reward disappearing

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#18]
**Plugin**: Specialized Crates 3.2.4
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Velocity**: velocity-proxy-3.1.2-SNAPSHOT-all
**Java Version**: jdk-11.0.15.1
**Explanation**: If you insert a mod item while there are items in rewards, the lore and nbt-tags of the previous item will disappear.
**Video**: https://youtu.be/xMpl2eGKai8

**Comment by ThePM2** [comment]
has been fixed on V3.2.5
