### ISSUE TITLE
[AC] Armor Stand animation bug.

### ISSUE THREAD

**Issue by slvlr** [slvlr/PM2-Plugins#2]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?
Advanced Crates

**Versions:**
 - Server Version: 1.19.3
 - Plugin Version: 3.6.1 & 3.6.2

**Describe the bug**
Armour stands are spamming the animations. 
Backdating to version 3.6.0 fixes this.

**To Reproduce**
Open the crate and start the animation.

**Expected behavior**
Animation to show correctly without displaying armor stands.

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://cdn.discordapp.com/attachments/1054818264850628699/1054818398984487012/image.png)

**Error / Logs**
N/A

**Comment by ThePM2** [comment]
Issue resolved on V3.6.3
Described issue was affecting versions 1.17-1.19.2
