### ISSUE TITLE
Unable to add sounds to new crates in sounds.yml

### ISSUE THREAD

**Issue by Firosee** [slvlr/PM2-Plugins#20]
**What plugin is this ticket in relation to?**
AdvancedCrates

**Versions:**
 - Server Version: 1.16.5
 - Plugin Version: 3.6.9 (Latest as of making this ticket)

**Describe the bug**
Sounds.yml allows the ability to add sounds for crates, however there is no option for the Breakout animation for sounds for it, and when going to add your own, it does not work.

**To Reproduce**
Check the sounds.yml file and try a adding your own sound effect for the breakout crate

**Expected behavior**
A sound to play when you open the crat

**Comment by ThePM2** [comment]
Added to default sounds.yml the existing sound configurations
