### ISSUE TITLE
Advanced Crates | Packet error and broken animations

### ISSUE THREAD

**Issue by Hadimhz** [slvlr/PM2-Plugins#22]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?
Advanced Crates

**Versions:**
 - Server Version: git-Purpur-1858 (MC: 1.19.2)
 - Plugin Version: 3.6.10

**Describe the bug**
Some animations simply don't work the way they're intended to. missing animations, along with flooding the console with packet errors.

**To Reproduce**

Place a create down.
Affected crates: Minion, Airstrike, breakout i tested and threw the error

**Expected behavior**
Animation to be completed with no issues.

**Screenshots**

**Error / Logs**
https://pastebin.com/jNn9WJt3

**Config File**
default config, nothing changed

**Crate File**
default config, nothing changed

**Comment by ThePM2** [comment]
Fixed in v3.7.1
