### ISSUE TITLE
AdvancedCrates - Server crashes when using 'Drag and Drop Reward' function

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#23]
**Plugin**: AdvancedCrates-3.7.2
**Operating System**: Windows 10
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
**Explanation**: If you set the reward item using '/ac config' -> Rewards -> Reward Editor -> 'Drag and Drop Rewards' function, the server will crash.
**Video**: https://youtu.be/ghhK-Aw5dO8
**Log**: https://pastebin.com/dEt7V7KS

**Comment by ThePM2** [comment]
old plugin version, please reopen if you still experience this issue
