### ISSUE TITLE
Specialized Crates - config.yml -> 'open-in-hand: true' problem

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#25]
**Plugin**: Specialized Crates 3.2.6
**Operating System**: Windows 10
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
**Explanation**: There is a bug where the crate is not opened when right clicking even if open-in-hand: true is set in config.yml.
Strangely, however, when Shift + Right Click, the crate is opened.
**Video**: https://youtu.be/Sxp67Lw3_wI

**Comment by ThePM2** [comment]
Added 'sneaking-for-open-in-hand: false' configuration to config.yml
