### ISSUE TITLE
Advanced Crates : Breaking plugin Issue with Oraxen

### ISSUE THREAD

**Issue by RenardFarceur** [slvlr/PM2-Plugins#35]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: Paper 1.19.3 425
 - Plugin Version: AC 3.8.8

**Describe the bug**
There is an issue using AC on "Furnitures" Made with Oraxen  (latest version). They are made with a Barrier block. I 've try for month to delete this bug. But the solution is : Delete AC or Delete Oraxen (and i can't remove one). The issue is only with the LEFT click (for the preview) not the Right click. 

**To Reproduce**
Download Oraxen, put a furniture on the ground (any furniture, they all don't work), try to preview : it don't work

**Expected behavior**
Preview the crate as AC should do. Have the Oraxen support :c

**Screenshots**
https://zupimages.net/up/23/10/eyw0.png (my crates) replaced by Diamond Block to make the crates work

**Error / Logs**
No error or any problem with log

**Config File**
I've reset my config file to see if it comes from there : nothing change, it's the config from scrap.

**Crate File**
No crate work on these furniture for the preview ...

**Comment by ThePM2** [comment]
I believe I was doing some testing with itemsadder, worked there fine on the newest, possibly have made changes since then and now it should work. If this is still an issue please reopen
