### ISSUE TITLE
Bonus Rewards Placeholder not working + Right clicking to open lootbox doesnt work

### ISSUE THREAD

**Issue by Rhys00** [slvlr/PM2-Plugins#36]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.8.8.
 - Plugin Version: 3.8.8

**Describe the bug**
The Bonus Reward placeholder no longer works in the latest updates, and also you cant right click the lootbox to open it anymore you have to look at the floor and right click which is annoying for many players. 

**To Reproduce**
Follow what I said above. 

**Expected behavior**

**Screenshots**
https://prnt.sc/IvXQsQJ187Xr

**Error / Logs**
No errors but here is latest log https://paste.helpch.at/dohuqudafu.makefile

**Config File**
https://paste.helpch.at/azebakogok.yaml

**Crate File**
https://paste.helpch.at/etabevelad.yaml

**Comment by Rhys00** [comment]
After testing more, the bonus placeholder only gets broken if the final message is "FinalMessageToOpener" so the opener can only see it. Also fixed the right click open by making OnlyPlacable false

**Comment by ThePM2** [comment]
has been fixed since then
