### ISSUE TITLE
longevity of advanced crates

### ISSUE THREAD

**Issue by datarat010** [slvlr/PM2-Plugins#40]
**What plugin are you requesting a feature for?**
Advanced Crates.

**Describe what you would like added to the plugin**
I am inquiring abou t the longevity of the advanced crate plugin . it seems discord is full of people saying that it is no  longer being supported

**Comment by ThePM2** [comment]
At the start of summer we came back, were mainly focused on discord tickets, closing these ones now. For anyone else reading this, we are actively once again working on our plugins with more dedication that ever before!
