### ISSUE TITLE
Pouches not working on 1.20

### ISSUE THREAD

**Issue by Domm1** [slvlr/PM2-Plugins#47]
**What plugin is this ticket in relation to?**
 Advanced Crates

**Versions:**
 - Paper version git-Paper-57 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 437e8da)
 - AdvancedCrates  3.9.5
 
**Describe the bug**
I can open pouch but nothing happens, no visual effects or rewards are given.

**To Reproduce**
Open pouch,

**Error / Logs**
https://pastebin.com/j2TTdQh7

**Config File**
https://pastebin.com/3THiQ0TN

**Crate File**
https://pastebin.com/SHEspaX8

**Comment by ThePM2** [comment]
Fixed
