### ISSUE TITLE
[AdvancedCrates] Cannot preview rewards

### ISSUE THREAD

**Issue by Biquaternions** [slvlr/PM2-Plugins#48]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: Purpur 1.19.4 & 1.20.1
 - Plugin Version: 3.9.12

**Describe the bug**
When left-clicking a crate (preview rewards) nothing happens and the console prints a thread exception

**To Reproduce**
Left click a crate (Tested with empty hand and AirStrike default crate)

**Expected behavior**
The preview menu should open, like older versions

**Error / Logs**
[Error](https://pastebin.com/s6Vhbejq)

**Config File**
[Config](https://pastebin.com/i2CP2UUz)

**Crate File**
[AirStrike.yml](https://pastebin.com/N3fR0iZM)

**Comment by 77Romain77** [comment]
Same issue for me in 1.16.5 with same plugin version

**Comment by ThePM2** [comment]
Issue fixed. Please update to a newer version
