### ISSUE TITLE
[Advanced Crates] Commands Rewards is executed randomly several times by the console

### ISSUE THREAD

**Issue by 77Romain77** [slvlr/PM2-Plugins#49]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.16.5
 - Plugin Version: 3.9.12

**Describe the bug**
When I use rewards via commands, randomly, the command is executed several times by the console. As a result, the rewards are received multiple times. 
I've already seen a player receive the reward up to 4 times (the command was executed 4 times by the console).

**To Reproduce**
Just need to open a lot of crates and see that the reward command has been executed several times. This is quite rare, so I opened a good number of crates to reproduce the bug.

**Expected behavior**
A fix to avoid duplicate rewards via commands.

**Screenshots**
![Capture d’écran 2023-07-02 195027](https://github.com/slvlr/PM2-Plugins/assets/113790889/9f103268-d33d-4047-a0e8-4b1e1ba36962)
![Capture d’écran 2023-06-30 005830](https://github.com/slvlr/PM2-Plugins/assets/113790889/bcd4dcc7-4a7f-4fb1-aab5-1b1419b7f8b1)

In both screen, we can see that I've received 2 rewards for the same crate (the 2 commands were executed at the same time). 

**Error / Logs**
No Error.

**Config File**
https://pastebin.com/1PVRbXUJ

**Crate File**
https://pastebin.com/bPV2cm4r

**Comment by TeoSaloufardos** [comment]
I have the same issue

**Comment by ThePM2** [comment]
update coming out today that should fix this
