### ISSUE TITLE
[AdvancedCrates] Double with ',' bug

### ISSUE THREAD

**Issue by moda84** [slvlr/PM2-Plugins#52]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?
Advanced Crates
**Versions:**
 - Server Version:
 Current: git-Purpur-2006 (MC: 1.20.1)*
Previous: git-Purpur-2001 (MC: 1.20.1)
 - Plugin Version:
3.9.12

**Describe the bug**
Error in console
![image](https://github.com/slvlr/PM2-Plugins/assets/44532692/210d55f4-0473-490b-9da5-281bd045ed82)

**README!** Clear and load defaults not help. Error in double. Crate, line 1137.
line 1137 parseDouble from number with a comma [,] e.g. 15,00, but double use only numbers with dot [.]
For full info check my ticket in discord "ticket-ac-1300"
![image](https://github.com/slvlr/PM2-Plugins/assets/44532692/593e6d28-5c99-4f95-a686-06b02efabffa)

**To Reproduce**
1. Player Left Click on crates
2. Preview of crates not open
3. See console error

**Expected behavior**
Player need see preview of crates

**Screenshots**
![image](https://github.com/slvlr/PM2-Plugins/assets/44532692/e9e6d785-ee42-492e-9589-5b56ba1dab92)

**Error / Logs**
Please post any errors / server log to https://pastebin.com and provide your Pastebin URL.
![image](https://github.com/slvlr/PM2-Plugins/assets/44532692/88325c06-0ab9-4f4d-b12a-418ad3f690c9)

**Config File**
Please post your config file to https://pastebin.com and provide your Pastebin URL.
https://pastebin.com/WNdKBq4s
**Crate File**
Please upload the crate files that you are having issues with to https://pastebin.com and provide your Pastebin URL.
https://pastebin.com/8sF7kwS8

**Comment by ThePM2** [comment]
posted update. Please use version 3.9.13 or newer
