### ISSUE TITLE
CRATE PREVIEW ERROR AND LORE ERROR

### ISSUE THREAD

**Issue by Regwield** [slvlr/PM2-Plugins#53]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?

**Versions:**
 - Server Version: 1.19.3
 - Plugin Version: 3.9.12

**Describe the bug**
When I left click the crate to preview it while I dont have the key, I get this error. And even if manage to open the review page by spamming left click for like 30-40 secs, I don't see any item lores. I only see their names not lores.

**Expected behavior**
Players should be able to review the crate and should be able to see item lores.

**Screenshots**
This is the lore I need to see ![image](https://github.com/slvlr/PM2-Plugins/assets/97476291/474b08a7-bc89-4538-8b2f-f5836e4a8c09)

This is what I see ![image2](https://github.com/slvlr/PM2-Plugins/assets/97476291/6c2892ba-b903-42cb-8404-e97b648121f8)

**Error / Logs**
Error: https://pastebin.com/4bXbJHQR

**Config File**
https://pastebin.com/C6iqggKM

**Crate File**
[Please upload the crate files that you are having issues with to https://pastebin.com and provide your Pastebin URL.](https://pastebin.com/tskPiag3)

**Comment by ThePM2** [comment]
posted plugin update. Please use 3.9.13 or newer
