### ISSUE TITLE
Warns and failed to give items in latest update

### ISSUE THREAD

**Issue by tomhmagic** [slvlr/PM2-Plugins#54]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.20.1
 - Plugin Version: 3.9.13

**Describe the bug**
Most animations are giving console warns and not giving the items. One animation also stops at the end of the animation.

**To Reproduce**
Steps to reproduce the behavior: Change animation of crate to any of the listed ones with warns in my error logs

**Expected behavior**
No warns and items given.

**Screenshots**
N/A

**Error / Logs**
[Please post any errors / server log to https://pastebin.com and provide your Pastebin URL.]
https://pastebin.com/uYcLc8BD

**Config File**
[Please post your config file to https://pastebin.com and provide your Pastebin URL.]
https://pastebin.com/9qn6QECp
**Crate File**
[[Please upload the crate files that you are having issues with to https://pastebin.com and provide your Pastebin URL.]
https://pastebin.com/RxRMSs4D

**Comment by ThePM2** [comment]
fixed in latest version
