### ISSUE TITLE
Rewards do not go into the player's inventory

### ISSUE THREAD

**Issue by QuestionCatcher** [slvlr/PM2-Plugins#58]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?
AdvancedCrates

**Versions:**
 - Server Version: 1.16.5, Purpur1171
 - Plugin Version: 3.9.17, 3.9.16

**Describe the bug**
3.9.17 - When a player opens a crate immediately after the previous animation ends, he does not receive a reward.
3.9.16 - The crate opens, the animation works correctly, however, the prize does not go to the player's inventory in any case.

**To Reproduce**
For version 3.9.17:
1. setup crate
2. open crate
3. wait until the end of animation
4. Immediately after completing the animation(receiving the reward), open another crate
5. No rewards from second crate.

For version 3.9.16
1. Setup crate
2. Open crate
3. Wait until the end of animation
4. Message about the reward appears in chat but does not go into the player's inventory

**Expected behavior**
The reward in both cases should go to the inventory no matter at what time the boxes were opened
The plugin works properly on version 3.9.15

**Screenshots**

**Error / Logs**
In console there is no errors, warns or any other mesages apart from those about the correct loading of the plugin.(before, during and after opening crates/starting server)

**Config File**
https://pastebin.com/MVDjjGAB

**Crate File**
https://pastebin.com/FQygPcKv - crate 1
https://pastebin.com/57pE5uhV - crate 2
https://pastebin.com/e3w8mg9Z - crate 3
https://pastebin.com/SLbTcR6g - crate 4
https://pastebin.com/uUpp5Ytm - crate 5
https://pastebin.com/CStMaXQe - crate 6

**Comment by Projecki** [comment]
I am also experiencing this issue on server version 1.20.1

**Comment by QuestionCatcher** [comment]
UPDATE:
For newest version of plugin which is 3.9.18 there is still a problem with awarding prizes after opening the crate.

**Comment by AlfreDGR** [comment]
I am also experiencing this issue on server version 1.20.1

**Comment by ThePM2** [comment]
Fixed in V3.9.19
