### ISSUE TITLE
in the item name . This item will cause an error when using reward drag & drop.

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#6]
**Plugin**: SpecializedCrates-3.1.7
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
**Explanation**: in the item name . This item will cause an error when using reward drag & drop.
**Video**: https://youtu.be/XeQfsqSlAmc
**crate file**: https://pastebin.com/sdfMh28b

**Comment by ThePM2** [comment]
Fix will be present in version 3.2.2
