### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by stephan77** [slvlr/PM2-Plugins#66]
**What plugin is this ticket in relation to?**
 Advanced Crates?

**Versions:**
 - Server Version: Paper 1.20.2 238
 - Plugin Version: 3.9.22

**Describe the bug**

de.tr7zw.advancedcrates.nbtapi.NBTItem.getCompound() returns null, add a null check before the toString() call.

**Error / Logs**
[log](https://pastebin.com/miaKbwzP)

**Comment by ThePM2** [comment]
Updated
