### ISSUE TITLE
Adding new rewards to the crate does not work

### ISSUE THREAD

**Issue by nasiridrishi** [slvlr/PM2-Plugins#67]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: git-Paper-241 (MC: 1.20.2)
 - Plugin Version: 3.9.22

**Describe the bug**
Not able to drag and drop new rewards in crates.

**To Reproduce**
1. Go to /ac config
2. Go to any crate and go to reward editor drag and drop option
3. try adding any item custom or vanilla
4. click on save button.(doesn't work)

**Expected behavior**
Should save added item in drag and drop menu

**Screenshots**
https://i.imgur.com/UxSo3WN.png

**Error / Logs**
https://mclo.gs/i6Xf3WF

**Config File**
https://mclo.gs/jIMHdUD

**Crate File**
https://mclo.gs/hiThwfG

**Comment by ThePM2** [comment]
Thank you for the report, issue will be fixed in the next update

**Comment by nasiridrishi** [comment]
when?
