### ISSUE TITLE
Window closes after item results in 'INV_CSGO' animations are very slow

### ISSUE THREAD

**Issue by geumu** [slvlr/PM2-Plugins#7]
**Plugin**: SpecializedCrates-3.1.7
**Operating System**: Windows 10 
**Bukkit Version**: arclight-forge-1.16.5-1.0.25-SNAPSHOT
**Java Version**: jdk-11.0.15.1
**Explanation**: Window closes after item results in 'INV_CSGO' animations are very slow. We need the ability to fix this.
close-speed does not control the speed at which the window closes, but rather the time at which the result is finalized.
**Video**: https://youtu.be/GPoex2ii9-g

**Comment by ThePM2** [comment]
Added an additional configuration final-panel-tick-length, read more about the update here;
https://www.spigotmc.org/resources/9047/update?update=483584
