### ISSUE TITLE
Crates have been removed

### ISSUE THREAD

**Issue by KikyoC** [slvlr/PM2-Plugins#72]
**What plugin is this ticket in relation to?**
Are you using Specialized Crates, or Advanced Crates?
AC-1493

**Versions:**
 - Server Version: 1.8.8 (ispigot)
 - Plugin Version: 3.9.24

**Describe the bug**
I set up 5 Crates and 4 of them have been removed for no reason

**To Reproduce**
I don't really know how to reproduce it

**Expected behavior**
Crates are not supposed to unregister themselves

**Screenshots**

**Error / Logs**
Please post any errors / server log to https://pastebin.com and provide your Pastebin URL.

**Config File**
Please post your config file to https://pastebin.com and provide your Pastebin URL.
https://pastebin.com/tzkBPuLL

**Comment by ThePM2** [comment]
Truly not sure what to say. Odd behavior, no other reports of this. Will not be further investigated than this for now unless there are more reports regarding it due to lack of steps to reproduce and possibility of user error
