### ISSUE TITLE
RewardsDon'tRepeat Not Working

### ISSUE THREAD

**Issue by itzrobotix** [slvlr/PM2-Plugins#75]
**What plugin is this ticket in relation to?**
Advanced Crates

**Versions:**
 - Server Version: 1.16.5 (Arclight)
 - Plugin Version: 3.9.20 (Latest that works with my Java version)

**Describe the bug**
I have a crate in which I'm trying to give 3 rewards using the quick animation in which rewards can't repeat however the rewardsdontrepeat config option just isn't working and rewards are able to repeat.
Tried all solutions provided by the support staff who have been very helpful who have now suggested I create this issue.

**To Reproduce**
Run a server on version 1.16.5, a crate with the quick animation and rewardsdontrepeat set to true with a size of 3.

**Expected behavior**
The rewards shouldn't be able to repeat.

**Screenshots**
<img width="736" alt="Screenshot 2023-11-26 at 21 39 26" src="https://github.com/slvlr/PM2-Plugins/assets/78166117/e558d7d2-6d80-4757-90f0-0f1b718b0e6e">

**Error / Logs**
No errors or logs in console are generated.

**Config File**
https://pastebin.com/uedb9NWY

**Crate File**
https://pastebin.com/yyh15rap

**Comment by ThePM2** [comment]
fixed
