### ISSUE TITLE
Plugin doesnt works

### ISSUE THREAD

**Issue by GinoCarino** [slvlr/PM2-Plugins#98]
Advanced Crates

**Versions:**
 - Server Version: 1.21
 - Plugin Version: 4.0.0-B4

**Describe the bug**
Plugin is red in the plugin list

**To Reproduce**
Steps to reproduce the behavior: 1.21 server

**Expected behavior**
Use the plugin

**Screenshots**
![Screenshot 2024-06-27 202427](https://github.com/slvlr/PM2-Plugins/assets/132331890/dc56d503-b1e1-4555-97cb-ad2f1f60314a)

**Error / Logs**
https://pastebin.com/gEF5iRpS (there are other plugins dont work)

**Config File**
https://pastebin.com/Af9CKEj2

**Crate File**
pl doesnt works

**Comment by ThePM2** [comment]
Issue should be fixed in V4.0.0-B5, reopen the ticket if issue is still present
